// Copyright © 2021 The Things Industries B.V.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: thethings/json/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate marshalers for all messages and enums in this file.
	// Message options can be used to override this.
	MarshalerAll *bool `protobuf:"varint,1,opt,name=marshaler_all,json=marshalerAll" json:"marshaler_all,omitempty"`
	// Generate unmarshalers for all messages and enums in this file.
	// Message options can be used to override this.
	UnmarshalerAll *bool `protobuf:"varint,2,opt,name=unmarshaler_all,json=unmarshalerAll" json:"unmarshaler_all,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetMarshalerAll() bool {
	if x != nil && x.MarshalerAll != nil {
		return *x.MarshalerAll
	}
	return false
}

func (x *FileOptions) GetUnmarshalerAll() bool {
	if x != nil && x.UnmarshalerAll != nil {
		return *x.UnmarshalerAll
	}
	return false
}

type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate a marshaler for this message.
	Marshaler *bool `protobuf:"varint,1,opt,name=marshaler" json:"marshaler,omitempty"`
	// Generate an unmarshaler for this message.
	Unmarshaler *bool `protobuf:"varint,2,opt,name=unmarshaler" json:"unmarshaler,omitempty"`
	// Treat this message as a wrapper for the value field inside it.
	Wrapper       *bool `protobuf:"varint,3,opt,name=wrapper" json:"wrapper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *MessageOptions) GetMarshaler() bool {
	if x != nil && x.Marshaler != nil {
		return *x.Marshaler
	}
	return false
}

func (x *MessageOptions) GetUnmarshaler() bool {
	if x != nil && x.Unmarshaler != nil {
		return *x.Unmarshaler
	}
	return false
}

func (x *MessageOptions) GetWrapper() bool {
	if x != nil && x.Wrapper != nil {
		return *x.Wrapper
	}
	return false
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom marshaler function. Specified as github.com/username/repo/package.FuncName.
	MarshalerFunc *string `protobuf:"bytes,1,opt,name=marshaler_func,json=marshalerFunc" json:"marshaler_func,omitempty"`
	// Custom unmarshaler function. Specified as github.com/username/repo/package.FuncName.
	UnmarshalerFunc *string `protobuf:"bytes,2,opt,name=unmarshaler_func,json=unmarshalerFunc" json:"unmarshaler_func,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetMarshalerFunc() string {
	if x != nil && x.MarshalerFunc != nil {
		return *x.MarshalerFunc
	}
	return ""
}

func (x *FieldOptions) GetUnmarshalerFunc() string {
	if x != nil && x.UnmarshalerFunc != nil {
		return *x.UnmarshalerFunc
	}
	return ""
}

type OneofOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{3}
}

type EnumOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate a marshaler for this enum.
	Marshaler *bool `protobuf:"varint,1,opt,name=marshaler" json:"marshaler,omitempty"`
	// Always marshal as a number.
	MarshalAsNumber *bool `protobuf:"varint,2,opt,name=marshal_as_number,json=marshalAsNumber" json:"marshal_as_number,omitempty"`
	// Always marshal as a string.
	MarshalAsString *bool `protobuf:"varint,3,opt,name=marshal_as_string,json=marshalAsString" json:"marshal_as_string,omitempty"`
	// Generate an unmarshaler for this enum.
	Unmarshaler *bool `protobuf:"varint,4,opt,name=unmarshaler" json:"unmarshaler,omitempty"`
	// Consider string values with this prefix when unmarshaling.
	Prefix        *string `protobuf:"bytes,5,opt,name=prefix" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumOptions) Reset() {
	*x = EnumOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumOptions) ProtoMessage() {}

func (x *EnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumOptions.ProtoReflect.Descriptor instead.
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *EnumOptions) GetMarshaler() bool {
	if x != nil && x.Marshaler != nil {
		return *x.Marshaler
	}
	return false
}

func (x *EnumOptions) GetMarshalAsNumber() bool {
	if x != nil && x.MarshalAsNumber != nil {
		return *x.MarshalAsNumber
	}
	return false
}

func (x *EnumOptions) GetMarshalAsString() bool {
	if x != nil && x.MarshalAsString != nil {
		return *x.MarshalAsString
	}
	return false
}

func (x *EnumOptions) GetUnmarshaler() bool {
	if x != nil && x.Unmarshaler != nil {
		return *x.Unmarshaler
	}
	return false
}

func (x *EnumOptions) GetPrefix() string {
	if x != nil && x.Prefix != nil {
		return *x.Prefix
	}
	return ""
}

type EnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value to emit when marshaling as string.
	Value *string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	// Aliases to accept when unmarshaling from string.
	Aliases       []string `protobuf:"bytes,2,rep,name=aliases" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValueOptions) Reset() {
	*x = EnumValueOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValueOptions) ProtoMessage() {}

func (x *EnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValueOptions.ProtoReflect.Descriptor instead.
func (*EnumValueOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *EnumValueOptions) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *EnumValueOptions) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{6}
}

type MethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_thethings_json_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_thethings_json_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_thethings_json_annotations_proto_rawDescGZIP(), []int{7}
}

var file_thethings_json_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.file",
		Tag:           "bytes,51885,opt,name=file",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.message",
		Tag:           "bytes,51885,opt,name=message",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.field",
		Tag:           "bytes,51885,opt,name=field",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.oneof",
		Tag:           "bytes,51885,opt,name=oneof",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*EnumOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.enum",
		Tag:           "bytes,51885,opt,name=enum",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*EnumValueOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.enum_value",
		Tag:           "bytes,51885,opt,name=enum_value",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.service",
		Tag:           "bytes,51885,opt,name=service",
		Filename:      "thethings/json/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         51885,
		Name:          "thethings.json.method",
		Tag:           "bytes,51885,opt,name=method",
		Filename:      "thethings/json/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional thethings.json.FileOptions file = 51885;
	E_File = &file_thethings_json_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional thethings.json.MessageOptions message = 51885;
	E_Message = &file_thethings_json_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional thethings.json.FieldOptions field = 51885;
	E_Field = &file_thethings_json_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional thethings.json.OneofOptions oneof = 51885;
	E_Oneof = &file_thethings_json_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional thethings.json.EnumOptions enum = 51885;
	E_Enum = &file_thethings_json_annotations_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional thethings.json.EnumValueOptions enum_value = 51885;
	E_EnumValue = &file_thethings_json_annotations_proto_extTypes[5]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional thethings.json.ServiceOptions service = 51885;
	E_Service = &file_thethings_json_annotations_proto_extTypes[6]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional thethings.json.MethodOptions method = 51885;
	E_Method = &file_thethings_json_annotations_proto_extTypes[7]
)

var File_thethings_json_annotations_proto protoreflect.FileDescriptor

const file_thethings_json_annotations_proto_rawDesc = "" +
	"\n" +
	" thethings/json/annotations.proto\x12\x0ethethings.json\x1a google/protobuf/descriptor.proto\"[\n" +
	"\vFileOptions\x12#\n" +
	"\rmarshaler_all\x18\x01 \x01(\bR\fmarshalerAll\x12'\n" +
	"\x0funmarshaler_all\x18\x02 \x01(\bR\x0eunmarshalerAll\"j\n" +
	"\x0eMessageOptions\x12\x1c\n" +
	"\tmarshaler\x18\x01 \x01(\bR\tmarshaler\x12 \n" +
	"\vunmarshaler\x18\x02 \x01(\bR\vunmarshaler\x12\x18\n" +
	"\awrapper\x18\x03 \x01(\bR\awrapper\"`\n" +
	"\fFieldOptions\x12%\n" +
	"\x0emarshaler_func\x18\x01 \x01(\tR\rmarshalerFunc\x12)\n" +
	"\x10unmarshaler_func\x18\x02 \x01(\tR\x0funmarshalerFunc\"\x0e\n" +
	"\fOneofOptions\"\xbd\x01\n" +
	"\vEnumOptions\x12\x1c\n" +
	"\tmarshaler\x18\x01 \x01(\bR\tmarshaler\x12*\n" +
	"\x11marshal_as_number\x18\x02 \x01(\bR\x0fmarshalAsNumber\x12*\n" +
	"\x11marshal_as_string\x18\x03 \x01(\bR\x0fmarshalAsString\x12 \n" +
	"\vunmarshaler\x18\x04 \x01(\bR\vunmarshaler\x12\x16\n" +
	"\x06prefix\x18\x05 \x01(\tR\x06prefix\"B\n" +
	"\x10EnumValueOptions\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\"\x10\n" +
	"\x0eServiceOptions\"\x0f\n" +
	"\rMethodOptions:O\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xad\x95\x03 \x01(\v2\x1b.thethings.json.FileOptionsR\x04file:[\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xad\x95\x03 \x01(\v2\x1e.thethings.json.MessageOptionsR\amessage:S\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xad\x95\x03 \x01(\v2\x1c.thethings.json.FieldOptionsR\x05field:S\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\xad\x95\x03 \x01(\v2\x1c.thethings.json.OneofOptionsR\x05oneof:O\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\xad\x95\x03 \x01(\v2\x1b.thethings.json.EnumOptionsR\x04enum:d\n" +
	"\n" +
	"enum_value\x12!.google.protobuf.EnumValueOptions\x18\xad\x95\x03 \x01(\v2 .thethings.json.EnumValueOptionsR\tenumValue:[\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xad\x95\x03 \x01(\v2\x1e.thethings.json.ServiceOptionsR\aservice:W\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xad\x95\x03 \x01(\v2\x1d.thethings.json.MethodOptionsR\x06methodB?Z=github.com/TheThingsIndustries/protoc-gen-go-json/annotations"

var (
	file_thethings_json_annotations_proto_rawDescOnce sync.Once
	file_thethings_json_annotations_proto_rawDescData []byte
)

func file_thethings_json_annotations_proto_rawDescGZIP() []byte {
	file_thethings_json_annotations_proto_rawDescOnce.Do(func() {
		file_thethings_json_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thethings_json_annotations_proto_rawDesc), len(file_thethings_json_annotations_proto_rawDesc)))
	})
	return file_thethings_json_annotations_proto_rawDescData
}

var file_thethings_json_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_thethings_json_annotations_proto_goTypes = []any{
	(*FileOptions)(nil),                   // 0: thethings.json.FileOptions
	(*MessageOptions)(nil),                // 1: thethings.json.MessageOptions
	(*FieldOptions)(nil),                  // 2: thethings.json.FieldOptions
	(*OneofOptions)(nil),                  // 3: thethings.json.OneofOptions
	(*EnumOptions)(nil),                   // 4: thethings.json.EnumOptions
	(*EnumValueOptions)(nil),              // 5: thethings.json.EnumValueOptions
	(*ServiceOptions)(nil),                // 6: thethings.json.ServiceOptions
	(*MethodOptions)(nil),                 // 7: thethings.json.MethodOptions
	(*descriptorpb.FileOptions)(nil),      // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 10: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),     // 11: google.protobuf.OneofOptions
	(*descriptorpb.EnumOptions)(nil),      // 12: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 13: google.protobuf.EnumValueOptions
	(*descriptorpb.ServiceOptions)(nil),   // 14: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),    // 15: google.protobuf.MethodOptions
}
var file_thethings_json_annotations_proto_depIdxs = []int32{
	8,  // 0: thethings.json.file:extendee -> google.protobuf.FileOptions
	9,  // 1: thethings.json.message:extendee -> google.protobuf.MessageOptions
	10, // 2: thethings.json.field:extendee -> google.protobuf.FieldOptions
	11, // 3: thethings.json.oneof:extendee -> google.protobuf.OneofOptions
	12, // 4: thethings.json.enum:extendee -> google.protobuf.EnumOptions
	13, // 5: thethings.json.enum_value:extendee -> google.protobuf.EnumValueOptions
	14, // 6: thethings.json.service:extendee -> google.protobuf.ServiceOptions
	15, // 7: thethings.json.method:extendee -> google.protobuf.MethodOptions
	0,  // 8: thethings.json.file:type_name -> thethings.json.FileOptions
	1,  // 9: thethings.json.message:type_name -> thethings.json.MessageOptions
	2,  // 10: thethings.json.field:type_name -> thethings.json.FieldOptions
	3,  // 11: thethings.json.oneof:type_name -> thethings.json.OneofOptions
	4,  // 12: thethings.json.enum:type_name -> thethings.json.EnumOptions
	5,  // 13: thethings.json.enum_value:type_name -> thethings.json.EnumValueOptions
	6,  // 14: thethings.json.service:type_name -> thethings.json.ServiceOptions
	7,  // 15: thethings.json.method:type_name -> thethings.json.MethodOptions
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	8,  // [8:16] is the sub-list for extension type_name
	0,  // [0:8] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_thethings_json_annotations_proto_init() }
func file_thethings_json_annotations_proto_init() {
	if File_thethings_json_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thethings_json_annotations_proto_rawDesc), len(file_thethings_json_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 8,
			NumServices:   0,
		},
		GoTypes:           file_thethings_json_annotations_proto_goTypes,
		DependencyIndexes: file_thethings_json_annotations_proto_depIdxs,
		MessageInfos:      file_thethings_json_annotations_proto_msgTypes,
		ExtensionInfos:    file_thethings_json_annotations_proto_extTypes,
	}.Build()
	File_thethings_json_annotations_proto = out.File
	file_thethings_json_annotations_proto_goTypes = nil
	file_thethings_json_annotations_proto_depIdxs = nil
}
