// Copyright © 2021 The Things Industries B.V.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: enums.proto

package test

import (
	_ "github.com/TheThingsIndustries/protoc-gen-go-json/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegularEnum int32

const (
	RegularEnum_REGULAR_UNKNOWN RegularEnum = 0
	RegularEnum_REGULAR_A       RegularEnum = 1
	RegularEnum_REGULAR_B       RegularEnum = 2
)

// Enum value maps for RegularEnum.
var (
	RegularEnum_name = map[int32]string{
		0: "REGULAR_UNKNOWN",
		1: "REGULAR_A",
		2: "REGULAR_B",
	}
	RegularEnum_value = map[string]int32{
		"REGULAR_UNKNOWN": 0,
		"REGULAR_A":       1,
		"REGULAR_B":       2,
	}
)

func (x RegularEnum) Enum() *RegularEnum {
	p := new(RegularEnum)
	*p = x
	return p
}

func (x RegularEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegularEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_proto_enumTypes[0].Descriptor()
}

func (RegularEnum) Type() protoreflect.EnumType {
	return &file_enums_proto_enumTypes[0]
}

func (x RegularEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegularEnum.Descriptor instead.
func (RegularEnum) EnumDescriptor() ([]byte, []int) {
	return file_enums_proto_rawDescGZIP(), []int{0}
}

type CustomEnum int32

const (
	CustomEnum_CUSTOM_UNKNOWN CustomEnum = 0
	CustomEnum_CUSTOM_V1_0    CustomEnum = 1
	CustomEnum_CUSTOM_V1_0_1  CustomEnum = 2
)

// Enum value maps for CustomEnum.
var (
	CustomEnum_name = map[int32]string{
		0: "CUSTOM_UNKNOWN",
		1: "CUSTOM_V1_0",
		2: "CUSTOM_V1_0_1",
	}
	CustomEnum_value = map[string]int32{
		"CUSTOM_UNKNOWN": 0,
		"CUSTOM_V1_0":    1,
		"CUSTOM_V1_0_1":  2,
	}
)

func (x CustomEnum) Enum() *CustomEnum {
	p := new(CustomEnum)
	*p = x
	return p
}

func (x CustomEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_proto_enumTypes[1].Descriptor()
}

func (CustomEnum) Type() protoreflect.EnumType {
	return &file_enums_proto_enumTypes[1]
}

func (x CustomEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomEnum.Descriptor instead.
func (CustomEnum) EnumDescriptor() ([]byte, []int) {
	return file_enums_proto_rawDescGZIP(), []int{1}
}

type CustomEnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         CustomEnum             `protobuf:"varint,1,opt,name=value,proto3,enum=thethings.json.test.CustomEnum" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomEnumValue) Reset() {
	*x = CustomEnumValue{}
	mi := &file_enums_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomEnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEnumValue) ProtoMessage() {}

func (x *CustomEnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_enums_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEnumValue.ProtoReflect.Descriptor instead.
func (*CustomEnumValue) Descriptor() ([]byte, []int) {
	return file_enums_proto_rawDescGZIP(), []int{0}
}

func (x *CustomEnumValue) GetValue() CustomEnum {
	if x != nil {
		return x.Value
	}
	return CustomEnum_CUSTOM_UNKNOWN
}

type MessageWithEnums struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Regular        RegularEnum            `protobuf:"varint,1,opt,name=regular,proto3,enum=thethings.json.test.RegularEnum" json:"regular,omitempty"`
	Regulars       []RegularEnum          `protobuf:"varint,2,rep,packed,name=regulars,proto3,enum=thethings.json.test.RegularEnum" json:"regulars,omitempty"`
	Custom         CustomEnum             `protobuf:"varint,3,opt,name=custom,proto3,enum=thethings.json.test.CustomEnum" json:"custom,omitempty"`
	Customs        []CustomEnum           `protobuf:"varint,4,rep,packed,name=customs,proto3,enum=thethings.json.test.CustomEnum" json:"customs,omitempty"`
	WrappedCustom  *CustomEnumValue       `protobuf:"bytes,5,opt,name=wrapped_custom,json=wrappedCustom,proto3" json:"wrapped_custom,omitempty"`
	WrappedCustoms []*CustomEnumValue     `protobuf:"bytes,6,rep,name=wrapped_customs,json=wrappedCustoms,proto3" json:"wrapped_customs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageWithEnums) Reset() {
	*x = MessageWithEnums{}
	mi := &file_enums_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithEnums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithEnums) ProtoMessage() {}

func (x *MessageWithEnums) ProtoReflect() protoreflect.Message {
	mi := &file_enums_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithEnums.ProtoReflect.Descriptor instead.
func (*MessageWithEnums) Descriptor() ([]byte, []int) {
	return file_enums_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithEnums) GetRegular() RegularEnum {
	if x != nil {
		return x.Regular
	}
	return RegularEnum_REGULAR_UNKNOWN
}

func (x *MessageWithEnums) GetRegulars() []RegularEnum {
	if x != nil {
		return x.Regulars
	}
	return nil
}

func (x *MessageWithEnums) GetCustom() CustomEnum {
	if x != nil {
		return x.Custom
	}
	return CustomEnum_CUSTOM_UNKNOWN
}

func (x *MessageWithEnums) GetCustoms() []CustomEnum {
	if x != nil {
		return x.Customs
	}
	return nil
}

func (x *MessageWithEnums) GetWrappedCustom() *CustomEnumValue {
	if x != nil {
		return x.WrappedCustom
	}
	return nil
}

func (x *MessageWithEnums) GetWrappedCustoms() []*CustomEnumValue {
	if x != nil {
		return x.WrappedCustoms
	}
	return nil
}

type MessageWithOneofEnums struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MessageWithOneofEnums_Regular
	//	*MessageWithOneofEnums_Custom
	//	*MessageWithOneofEnums_WrappedCustom
	Value         isMessageWithOneofEnums_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithOneofEnums) Reset() {
	*x = MessageWithOneofEnums{}
	mi := &file_enums_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithOneofEnums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithOneofEnums) ProtoMessage() {}

func (x *MessageWithOneofEnums) ProtoReflect() protoreflect.Message {
	mi := &file_enums_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithOneofEnums.ProtoReflect.Descriptor instead.
func (*MessageWithOneofEnums) Descriptor() ([]byte, []int) {
	return file_enums_proto_rawDescGZIP(), []int{2}
}

func (x *MessageWithOneofEnums) GetValue() isMessageWithOneofEnums_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MessageWithOneofEnums) GetRegular() RegularEnum {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofEnums_Regular); ok {
			return x.Regular
		}
	}
	return RegularEnum_REGULAR_UNKNOWN
}

func (x *MessageWithOneofEnums) GetCustom() CustomEnum {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofEnums_Custom); ok {
			return x.Custom
		}
	}
	return CustomEnum_CUSTOM_UNKNOWN
}

func (x *MessageWithOneofEnums) GetWrappedCustom() *CustomEnumValue {
	if x != nil {
		if x, ok := x.Value.(*MessageWithOneofEnums_WrappedCustom); ok {
			return x.WrappedCustom
		}
	}
	return nil
}

type isMessageWithOneofEnums_Value interface {
	isMessageWithOneofEnums_Value()
}

type MessageWithOneofEnums_Regular struct {
	Regular RegularEnum `protobuf:"varint,1,opt,name=regular,proto3,enum=thethings.json.test.RegularEnum,oneof"`
}

type MessageWithOneofEnums_Custom struct {
	Custom CustomEnum `protobuf:"varint,2,opt,name=custom,proto3,enum=thethings.json.test.CustomEnum,oneof"`
}

type MessageWithOneofEnums_WrappedCustom struct {
	WrappedCustom *CustomEnumValue `protobuf:"bytes,3,opt,name=wrapped_custom,json=wrappedCustom,proto3,oneof"`
}

func (*MessageWithOneofEnums_Regular) isMessageWithOneofEnums_Value() {}

func (*MessageWithOneofEnums_Custom) isMessageWithOneofEnums_Value() {}

func (*MessageWithOneofEnums_WrappedCustom) isMessageWithOneofEnums_Value() {}

var File_enums_proto protoreflect.FileDescriptor

const file_enums_proto_rawDesc = "" +
	"\n" +
	"\venums.proto\x12\x13thethings.json.test\x1a thethings/json/annotations.proto\"P\n" +
	"\x0fCustomEnumValue\x125\n" +
	"\x05value\x18\x01 \x01(\x0e2\x1f.thethings.json.test.CustomEnumR\x05value:\x06\xea\xaa\x19\x02\x18\x01\"\x9c\x03\n" +
	"\x10MessageWithEnums\x12:\n" +
	"\aregular\x18\x01 \x01(\x0e2 .thethings.json.test.RegularEnumR\aregular\x12<\n" +
	"\bregulars\x18\x02 \x03(\x0e2 .thethings.json.test.RegularEnumR\bregulars\x127\n" +
	"\x06custom\x18\x03 \x01(\x0e2\x1f.thethings.json.test.CustomEnumR\x06custom\x129\n" +
	"\acustoms\x18\x04 \x03(\x0e2\x1f.thethings.json.test.CustomEnumR\acustoms\x12K\n" +
	"\x0ewrapped_custom\x18\x05 \x01(\v2$.thethings.json.test.CustomEnumValueR\rwrappedCustom\x12M\n" +
	"\x0fwrapped_customs\x18\x06 \x03(\v2$.thethings.json.test.CustomEnumValueR\x0ewrappedCustoms\"\xe8\x01\n" +
	"\x15MessageWithOneofEnums\x12<\n" +
	"\aregular\x18\x01 \x01(\x0e2 .thethings.json.test.RegularEnumH\x00R\aregular\x129\n" +
	"\x06custom\x18\x02 \x01(\x0e2\x1f.thethings.json.test.CustomEnumH\x00R\x06custom\x12M\n" +
	"\x0ewrapped_custom\x18\x03 \x01(\v2$.thethings.json.test.CustomEnumValueH\x00R\rwrappedCustomB\a\n" +
	"\x05value*J\n" +
	"\vRegularEnum\x12\x13\n" +
	"\x0fREGULAR_UNKNOWN\x10\x00\x12\r\n" +
	"\tREGULAR_A\x10\x01\x12\r\n" +
	"\tREGULAR_B\x10\x02\x1a\b\xea\xaa\x19\x04\b\x00 \x00*s\n" +
	"\n" +
	"CustomEnum\x12\x12\n" +
	"\x0eCUSTOM_UNKNOWN\x10\x00\x12!\n" +
	"\vCUSTOM_V1_0\x10\x01\x1a\x10\xea\xaa\x19\f\n" +
	"\x031.0\x12\x051.0.0\x12\x1e\n" +
	"\rCUSTOM_V1_0_1\x10\x02\x1a\v\xea\xaa\x19\a\n" +
	"\x051.0.1\x1a\x0e\xea\xaa\x19\n" +
	"\x18\x01*\x06CUSTOMB@\xea\xaa\x19\x04\b\x01\x10\x01Z6github.com/TheThingsIndustries/protoc-gen-go-json/testb\x06proto3"

var (
	file_enums_proto_rawDescOnce sync.Once
	file_enums_proto_rawDescData []byte
)

func file_enums_proto_rawDescGZIP() []byte {
	file_enums_proto_rawDescOnce.Do(func() {
		file_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_proto_rawDesc), len(file_enums_proto_rawDesc)))
	})
	return file_enums_proto_rawDescData
}

var file_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enums_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_enums_proto_goTypes = []any{
	(RegularEnum)(0),              // 0: thethings.json.test.RegularEnum
	(CustomEnum)(0),               // 1: thethings.json.test.CustomEnum
	(*CustomEnumValue)(nil),       // 2: thethings.json.test.CustomEnumValue
	(*MessageWithEnums)(nil),      // 3: thethings.json.test.MessageWithEnums
	(*MessageWithOneofEnums)(nil), // 4: thethings.json.test.MessageWithOneofEnums
}
var file_enums_proto_depIdxs = []int32{
	1,  // 0: thethings.json.test.CustomEnumValue.value:type_name -> thethings.json.test.CustomEnum
	0,  // 1: thethings.json.test.MessageWithEnums.regular:type_name -> thethings.json.test.RegularEnum
	0,  // 2: thethings.json.test.MessageWithEnums.regulars:type_name -> thethings.json.test.RegularEnum
	1,  // 3: thethings.json.test.MessageWithEnums.custom:type_name -> thethings.json.test.CustomEnum
	1,  // 4: thethings.json.test.MessageWithEnums.customs:type_name -> thethings.json.test.CustomEnum
	2,  // 5: thethings.json.test.MessageWithEnums.wrapped_custom:type_name -> thethings.json.test.CustomEnumValue
	2,  // 6: thethings.json.test.MessageWithEnums.wrapped_customs:type_name -> thethings.json.test.CustomEnumValue
	0,  // 7: thethings.json.test.MessageWithOneofEnums.regular:type_name -> thethings.json.test.RegularEnum
	1,  // 8: thethings.json.test.MessageWithOneofEnums.custom:type_name -> thethings.json.test.CustomEnum
	2,  // 9: thethings.json.test.MessageWithOneofEnums.wrapped_custom:type_name -> thethings.json.test.CustomEnumValue
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_enums_proto_init() }
func file_enums_proto_init() {
	if File_enums_proto != nil {
		return
	}
	file_enums_proto_msgTypes[2].OneofWrappers = []any{
		(*MessageWithOneofEnums_Regular)(nil),
		(*MessageWithOneofEnums_Custom)(nil),
		(*MessageWithOneofEnums_WrappedCustom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_proto_rawDesc), len(file_enums_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_proto_goTypes,
		DependencyIndexes: file_enums_proto_depIdxs,
		EnumInfos:         file_enums_proto_enumTypes,
		MessageInfos:      file_enums_proto_msgTypes,
	}.Build()
	File_enums_proto = out.File
	file_enums_proto_goTypes = nil
	file_enums_proto_depIdxs = nil
}
