// Code generated by protoc-gen-go-json. DO NOT EDIT.
// versions:
// - protoc-gen-go-json v0.0.0-dev
// - protoc             v3.20.1
// source: fieldmask.proto

package test

import (
	golang "github.com/TheThingsIndustries/protoc-gen-go-json/golang"
	jsonplugin "github.com/TheThingsIndustries/protoc-gen-go-json/jsonplugin"
)

// UnmarshalProtoJSON unmarshals the MessageWithFieldMask message from JSON.
func (x *MessageWithFieldMask) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "field_mask", "fieldMask":
			s.AddField("field_mask")
			if s.ReadNil() {
				x.FieldMask = nil
				return
			}
			v := golang.UnmarshalFieldMask(s)
			if s.Err() != nil {
				return
			}
			x.FieldMask = v
		case "name":
			s.AddField("name")
			x.Name = s.ReadString()
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithFieldMask from JSON.
func (x *MessageWithFieldMask) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// UnmarshalProtoJSON unmarshals the MessageWithSubmessageWithFieldmask message from JSON.
func (x *MessageWithSubmessageWithFieldmask) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "submessage":
			s.AddField("submessage")
			if s.ReadNil() {
				x.Submessage = nil
				return
			}
			x.Submessage = &MessageWithFieldMask{}
			x.Submessage.UnmarshalProtoJSON(s.WithField("submessage", false))
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithSubmessageWithFieldmask from JSON.
func (x *MessageWithSubmessageWithFieldmask) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// UnmarshalProtoJSON unmarshals the MessageWithFieldmaskAndSubmessageWithFieldmask message from JSON.
func (x *MessageWithFieldmaskAndSubmessageWithFieldmask) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "field_mask", "fieldMask":
			s.AddField("field_mask")
			if s.ReadNil() {
				x.FieldMask = nil
				return
			}
			v := golang.UnmarshalFieldMask(s)
			if s.Err() != nil {
				return
			}
			x.FieldMask = v
		case "submessage":
			s.AddField("submessage")
			if s.ReadNil() {
				x.Submessage = nil
				return
			}
			// NOTE: MessageWithoutFieldMask does not seem to implement UnmarshalProtoJSON.
			var v MessageWithoutFieldMask
			golang.UnmarshalMessage(s, &v)
			x.Submessage = &v
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithFieldmaskAndSubmessageWithFieldmask from JSON.
func (x *MessageWithFieldmaskAndSubmessageWithFieldmask) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// UnmarshalProtoJSON unmarshals the MessageWithFieldmaskAndSubmessageWithoutFieldmask message from JSON.
func (x *MessageWithFieldmaskAndSubmessageWithoutFieldmask) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "field_mask", "fieldMask":
			s.AddField("field_mask")
			if s.ReadNil() {
				x.FieldMask = nil
				return
			}
			v := golang.UnmarshalFieldMask(s)
			if s.Err() != nil {
				return
			}
			x.FieldMask = v
		case "submessage":
			s.AddField("submessage")
			if s.ReadNil() {
				x.Submessage = nil
				return
			}
			x.Submessage = &MessageWithFieldMask{}
			x.Submessage.UnmarshalProtoJSON(s.WithField("submessage", false))
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithFieldmaskAndSubmessageWithoutFieldmask from JSON.
func (x *MessageWithFieldmaskAndSubmessageWithoutFieldmask) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}

// MarshalProtoJSON marshals the MessageWithSubmessageWithFieldmaskAndMarshaler message to JSON.
func (x *MessageWithSubmessageWithFieldmaskAndMarshaler) MarshalProtoJSON(s *jsonplugin.MarshalState) {
	if x == nil {
		s.WriteNil()
		return
	}
	s.WriteObjectStart()
	var wroteField bool
	if x.Submessage != nil || s.HasField("submessage") {
		s.WriteMoreIf(&wroteField)
		s.WriteObjectField("submessage")
		// NOTE: MessageWithFieldMask does not seem to implement MarshalProtoJSON.
		golang.MarshalMessage(s, x.Submessage)
	}
	s.WriteObjectEnd()
}

// MarshalJSON marshals the MessageWithSubmessageWithFieldmaskAndMarshaler to JSON.
func (x *MessageWithSubmessageWithFieldmaskAndMarshaler) MarshalJSON() ([]byte, error) {
	return jsonplugin.DefaultMarshalerConfig.Marshal(x)
}

// UnmarshalProtoJSON unmarshals the MessageWithSubmessageWithFieldmaskAndMarshaler message from JSON.
func (x *MessageWithSubmessageWithFieldmaskAndMarshaler) UnmarshalProtoJSON(s *jsonplugin.UnmarshalState) {
	if s.ReadNil() {
		return
	}
	s.ReadObject(func(key string) {
		switch key {
		default:
			s.ReadAny() // ignore unknown field
		case "submessage":
			s.AddField("submessage")
			if s.ReadNil() {
				x.Submessage = nil
				return
			}
			x.Submessage = &MessageWithFieldMask{}
			x.Submessage.UnmarshalProtoJSON(s.WithField("submessage", false))
		}
	})
}

// UnmarshalJSON unmarshals the MessageWithSubmessageWithFieldmaskAndMarshaler from JSON.
func (x *MessageWithSubmessageWithFieldmaskAndMarshaler) UnmarshalJSON(b []byte) error {
	return jsonplugin.DefaultUnmarshalerConfig.Unmarshal(b, x)
}
