name: Go Code

on:
  - push
  - pull_request

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.17"
      - name: Initialize Go module cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-
      - name: Clean Build
        run: make clean build
      - name: Go Test
        run: make test
