name: Go

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.24"
      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.50.0"
      - name: Clean and Build
        run: make clean build
      - name: Test
        run: make test
